#! /bin/bash

mkdir -p src/com/java/{v1/{random,activity,presenter},v2/{random,activity,presenter},v3/{random,activity,presenter},v4/{random,activity,presenter}}
cd ~/Desktop/src/com/java/v1/random
echo 'This is a test file 1 in v1 directory' > File1.java
echo 'This is a test file 2 in v1 directory' > File2.java
echo 'This is a test file 3 in v1 directory' > File3.java
echo 'This is a test file 4 in v1 directory' > File4.java
echo 'This is a test file 5 in v1 directory' > File5.java
echo 'This is a test file 6 in v1 directory' > File6.java
echo 'This is a test file 7 in v1 directory' > File7.java
echo 'This is a test file 8 in v1 directory' > File8.java
echo 'This is a test file 9 in v1 directory' > File9.java
echo 'This is a test file 0 in v1 directory' > File0.java
echo 'This is a test file 11 in v1 directory' > File11.java
echo 'This is a test file 12 in v1 directory' > File12.java
echo 'This is a test file 13 in v1 directory' > File13.java
echo 'This is a test file 14 in v1 directory' > File14.java
echo 'This is a test file 15 in v1 directory' > File15.java
echo 'This is a test file 16 in v1 directory' > File16.java
echo 'This is a test file 17 in v1 directory' > File17.java
echo 'This is a test file 18 in v1 directory' > File18.java
echo 'This is a test file 19 in v1 directory' > File19.java
echo 'This is a test file 10 in v1 directory' > File10.java
echo 'This is a test file 21 in v1 directory' > File21.java
echo 'This is a test file 22 in v1 directory' > File22.java
echo 'This is a test file 23 in v1 directory' > File23.java
echo 'This is a test file 24 in v1 directory' > File24.java
echo 'This is a test file 25 in v1 directory' > File25.java
echo 'This is a test file 26 in v1 directory' > File26.java
echo 'This is a test file 27 in v1 directory' > File27.java
echo 'This is a test file 28 in v1 directory' > File28.java
echo 'This is a test file 29 in v1 directory' > File29.java
echo 'This is a test file 20 in v1 directory' > File20.java
echo 'This is a test file 31 in v1 directory' > File31.java
echo 'This is a test file 32 in v1 directory' > File32.java
echo 'This is a test file 33 in v1 directory' > File33.java
echo 'This is a test file 34 in v1 directory' > File34.java
echo 'This is a test file 35 in v1 directory' > File35.java
echo 'This is a test file 36 in v1 directory' > File36.java
echo 'This is a test file 37 in v1 directory' > File37.java
echo 'This is a test file 38 in v1 directory' > File38.java
echo 'This is a test file 39 in v1 directory' > File39.java
echo 'This is a test file 30 in v1 directory' > File30.java

cd ~/Desktop/src/com/java/v2/random
echo 'This is a test file 1 in v2 directory' > File1.java
echo 'This is a test file 2 in v2 directory' > File2.java
echo 'This is a test file 3 in v2 directory' > File3.java
echo 'This is a test file 4 in v2 directory' > File4.java
echo 'This is a test file 5 in v2 directory' > File5.java
echo 'This is a test file 6 in v2 directory' > File6.java
echo 'This is a test file 7 in v2 directory' > File7.java
echo 'This is a test file 8 in v2 directory' > File8.java
echo 'This is a test file 9 in v2 directory' > File9.java
echo 'This is a test file 0 in v2 directory' > File0.java
echo 'This is a test file 11 in v2 directory' > File11.java
echo 'This is a test file 12 in v2 directory' > File12.java
echo 'This is a test file 13 in v2 directory' > File13.java
echo 'This is a test file 14 in v2 directory' > File14.java
echo 'This is a test file 15 in v2 directory' > File15.java
echo 'This is a test file 16 in v2 directory' > File16.java
echo 'This is a test file 17 in v2 directory' > File17.java
echo 'This is a test file 18 in v2 directory' > File18.java
echo 'This is a test file 19 in v2 directory' > File19.java
echo 'This is a test file 10 in v2 directory' > File10.java
echo 'This is a test file 21 in v2 directory' > File21.java
echo 'This is a test file 22 in v2 directory' > File22.java
echo 'This is a test file 23 in v2 directory' > File23.java
echo 'This is a test file 24 in v2 directory' > File24.java
echo 'This is a test file 25 in v2 directory' > File25.java
echo 'This is a test file 26 in v2 directory' > File26.java
echo 'This is a test file 27 in v2 directory' > File27.java
echo 'This is a test file 28 in v2 directory' > File28.java
echo 'This is a test file 29 in v2 directory' > File29.java
echo 'This is a test file 20 in v2 directory' > File20.java
echo 'This is a test file 31 in v2 directory' > File31.java
echo 'This is a test file 32 in v2 directory' > File32.java
echo 'This is a test file 33 in v2 directory' > File33.java
echo 'This is a test file 34 in v2 directory' > File34.java
echo 'This is a test file 35 in v2 directory' > File35.java
echo 'This is a test file 36 in v2 directory' > File36.java
echo 'This is a test file 37 in v2 directory' > File37.java
echo 'This is a test file 38 in v2 directory' > File38.java
echo 'This is a test file 39 in v2 directory' > File39.java
echo 'This is a test file 30 in v2 directory' > File30.java

cd ~/Desktop/src/com/java/v3/random
echo 'This is a test file 1 in v3 directory' > File1.java
echo 'This is a test file 2 in v3 directory' > File2.java
echo 'This is a test file 3 in v3 directory' > File3.java
echo 'This is a test file 4 in v3 directory' > File4.java
echo 'This is a test file 5 in v3 directory' > File5.java
echo 'This is a test file 6 in v3 directory' > File6.java
echo 'This is a test file 7 in v3 directory' > File7.java
echo 'This is a test file 8 in v3 directory' > File8.java
echo 'This is a test file 9 in v3 directory' > File9.java
echo 'This is a test file 0 in v3 directory' > File0.java
echo 'This is a test file 11 in v3 directory' > File11.java
echo 'This is a test file 12 in v3 directory' > File12.java
echo 'This is a test file 13 in v3 directory' > File13.java
echo 'This is a test file 14 in v3 directory' > File14.java
echo 'This is a test file 15 in v3 directory' > File15.java
echo 'This is a test file 16 in v3 directory' > File16.java
echo 'This is a test file 17 in v3 directory' > File17.java
echo 'This is a test file 18 in v3 directory' > File18.java
echo 'This is a test file 19 in v3 directory' > File19.java
echo 'This is a test file 10 in v3 directory' > File10.java
echo 'This is a test file 21 in v3 directory' > File21.java
echo 'This is a test file 22 in v3 directory' > File22.java
echo 'This is a test file 23 in v3 directory' > File23.java
echo 'This is a test file 24 in v3 directory' > File24.java
echo 'This is a test file 25 in v3 directory' > File25.java
echo 'This is a test file 26 in v3 directory' > File26.java
echo 'This is a test file 27 in v3 directory' > File27.java
echo 'This is a test file 28 in v3 directory' > File28.java
echo 'This is a test file 29 in v3 directory' > File29.java
echo 'This is a test file 20 in v3 directory' > File20.java
echo 'This is a test file 31 in v3 directory' > File31.java
echo 'This is a test file 32 in v3 directory' > File32.java
echo 'This is a test file 33 in v3 directory' > File33.java
echo 'This is a test file 34 in v3 directory' > File34.java
echo 'This is a test file 35 in v3 directory' > File35.java
echo 'This is a test file 36 in v3 directory' > File36.java
echo 'This is a test file 37 in v3 directory' > File37.java
echo 'This is a test file 38 in v3 directory' > File38.java
echo 'This is a test file 39 in v3 directory' > File39.java
echo 'This is a test file 30 in v3 directory' > File30.java

cd ~/Desktop/src/com/java/v4/random
echo 'This is a test file 1 in v4 directory' > File1.java
echo 'This is a test file 2 in v4 directory' > File2.java
echo 'This is a test file 3 in v4 directory' > File3.java
echo 'This is a test file 4 in v4 directory' > File4.java
echo 'This is a test file 5 in v4 directory' > File5.java
echo 'This is a test file 6 in v4 directory' > File6.java
echo 'This is a test file 7 in v4 directory' > File7.java
echo 'This is a test file 8 in v4 directory' > File8.java
echo 'This is a test file 9 in v4 directory' > File9.java
echo 'This is a test file 0 in v4 directory' > File0.java
echo 'This is a test file 11 in v4 directory' > File11.java
echo 'This is a test file 12 in v4 directory' > File12.java
echo 'This is a test file 13 in v4 directory' > File13.java
echo 'This is a test file 14 in v4 directory' > File14.java
echo 'This is a test file 15 in v4 directory' > File15.java
echo 'This is a test file 16 in v4 directory' > File16.java
echo 'This is a test file 17 in v4 directory' > File17.java
echo 'This is a test file 18 in v4 directory' > File18.java
echo 'This is a test file 19 in v4 directory' > File19.java
echo 'This is a test file 10 in v4 directory' > File10.java
echo 'This is a test file 21 in v4 directory' > File21.java
echo 'This is a test file 22 in v4 directory' > File22.java
echo 'This is a test file 23 in v4 directory' > File23.java
echo 'This is a test file 24 in v4 directory' > File24.java
echo 'This is a test file 25 in v4 directory' > File25.java
echo 'This is a test file 26 in v4 directory' > File26.java
echo 'This is a test file 27 in v4 directory' > File27.java
echo 'This is a test file 28 in v4 directory' > File28.java
echo 'This is a test file 29 in v4 directory' > File29.java
echo 'This is a test file 20 in v4 directory' > File20.java
echo 'This is a test file 31 in v4 directory' > File31.java
echo 'This is a test file 32 in v4 directory' > File32.java
echo 'This is a test file 33 in v4 directory' > File33.java
echo 'This is a test file 34 in v4 directory' > File34.java
echo 'This is a test file 35 in v4 directory' > File35.java
echo 'This is a test file 36 in v4 directory' > File36.java
echo 'This is a test file 37 in v4 directory' > File37.java
echo 'This is a test file 38 in v4 directory' > File38.java
echo 'This is a test file 39 in v4 directory' > File39.java
echo 'This is a test file 30 in v4 directory' > File30.java


cd ~/Desktop/src/com/java/v1/activity
echo 'This is a Test Activity 0 in v1 directory' > Test10Activity.java
echo 'This is a Test Activity 1 in v1 directory' > Test11Activity.java
echo 'This is a Test Activity 2 in v1 directory' > Test12Activity.java
echo 'This is a Test Activity 3 in v1 directory' > Test13Activity.java
echo 'This is a Test Activity 4 in v1 directory' > Test14Activity.java
echo 'This is a Test Activity 5 in v1 directory' > Test15Activity.java
echo 'This is a Test Activity 6 in v1 directory' > Test16Activity.java
echo 'This is a Test Activity 7 in v1 directory' > Test17Activity.java
echo 'This is a Test Activity 8 in v1 directory' > Test18Activity.java
echo 'This is a Test Activity 9 in v1 directory' > Test19Activity.java
echo 'This is a Test Activity 10 in v1 directory' > Test110Activity.java
echo 'This is a Test Activity 11 in v1 directory' > Test111Activity.java
echo 'This is a Test Activity 12 in v1 directory' > Test112Activity.java
echo 'This is a Test Activity 13 in v1 directory' > Test113Activity.java
echo 'This is a Test Activity 14 in v1 directory' > Test114Activity.java
echo 'This is a Test Activity 15 in v1 directory' > Test115Activity.java
echo 'This is a Test Activity 16 in v1 directory' > Test116Activity.java
echo 'This is a Test Activity 17 in v1 directory' > Test117Activity.java
echo 'This is a Test Activity 18 in v1 directory' > Test118Activity.java
echo 'This is a Test Activity 19 in v1 directory' > Test119Activity.java
echo 'This is a Test Activity 20 in v1 directory' > Test120Activity.java
echo 'This is a Test Activity 21 in v1 directory' > Test121Activity.java
echo 'This is a Test Activity 22 in v1 directory' > Test122Activity.java
echo 'This is a Test Activity 23 in v1 directory' > Test123Activity.java
echo 'This is a Test Activity 24 in v1 directory' > Test124Activity.java
echo 'This is a Test Activity 25 in v1 directory' > Test125Activity.java
echo 'This is a Test Activity 26 in v1 directory' > Test126Activity.java
echo 'This is a Test Activity 27 in v1 directory' > Test127Activity.java
echo 'This is a Test Activity 28 in v1 directory' > Test128Activity.java
echo 'This is a Test Activity 29 in v1 directory' > Test129Activity.java
echo 'This is a Test Activity 30 in v1 directory' > Test130Activity.java
echo 'This is a Test Activity 31 in v1 directory' > Test131Activity.java
echo 'This is a Test Activity 32 in v1 directory' > Test132Activity.java
echo 'This is a Test Activity 33 in v1 directory' > Test133Activity.java
echo 'This is a Test Activity 34 in v1 directory' > Test134Activity.java
echo 'This is a Test Activity 35 in v1 directory' > Test135Activity.java
echo 'This is a Test Activity 36 in v1 directory' > Test136Activity.java
echo 'This is a Test Activity 37 in v1 directory' > Test137Activity.java
echo 'This is a Test Activity 38 in v1 directory' > Test138Activity.java
echo 'This is a Test Activity 39 in v1 directory' > Test139Activity.java

cd ~/Desktop/src/com/java/v2/activity
echo 'This is a Test Activity 0 in v2 directory' > Test20Activity.java
echo 'This is a Test Activity 1 in v2 directory' > Test21Activity.java
echo 'This is a Test Activity 2 in v2 directory' > Test22Activity.java
echo 'This is a Test Activity 3 in v2 directory' > Test23Activity.java
echo 'This is a Test Activity 4 in v2 directory' > Test24Activity.java
echo 'This is a Test Activity 5 in v2 directory' > Test25Activity.java
echo 'This is a Test Activity 6 in v2 directory' > Test26Activity.java
echo 'This is a Test Activity 7 in v2 directory' > Test27Activity.java
echo 'This is a Test Activity 8 in v2 directory' > Test28Activity.java
echo 'This is a Test Activity 9 in v2 directory' > Test29Activity.java
echo 'This is a Test Activity 10 in v2 directory' > Test210Activity.java
echo 'This is a Test Activity 11 in v2 directory' > Test211Activity.java
echo 'This is a Test Activity 12 in v2 directory' > Test212Activity.java
echo 'This is a Test Activity 13 in v2 directory' > Test213Activity.java
echo 'This is a Test Activity 14 in v2 directory' > Test214Activity.java
echo 'This is a Test Activity 15 in v2 directory' > Test215Activity.java
echo 'This is a Test Activity 16 in v2 directory' > Test216Activity.java
echo 'This is a Test Activity 17 in v2 directory' > Test217Activity.java
echo 'This is a Test Activity 18 in v2 directory' > Test218Activity.java
echo 'This is a Test Activity 19 in v2 directory' > Test219Activity.java

cd ~/Desktop/src/com/java/v3/activity
echo 'This is a Test Activity 0 in v3 directory' > Test30Activity.java
echo 'This is a Test Activity 1 in v3 directory' > Test31Activity.java
echo 'This is a Test Activity 2 in v3 directory' > Test32Activity.java
echo 'This is a Test Activity 3 in v3 directory' > Test33Activity.java
echo 'This is a Test Activity 4 in v3 directory' > Test34Activity.java
echo 'This is a Test Activity 5 in v3 directory' > Test35Activity.java
echo 'This is a Test Activity 6 in v3 directory' > Test36Activity.java
echo 'This is a Test Activity 7 in v3 directory' > Test37Activity.java
echo 'This is a Test Activity 8 in v3 directory' > Test38Activity.java
echo 'This is a Test Activity 9 in v3 directory' > Test39Activity.java
echo 'This is a Test Activity 10 in v3 directory' > Test310Activity.java
echo 'This is a Test Activity 11 in v3 directory' > Test311Activity.java
echo 'This is a Test Activity 12 in v3 directory' > Test312Activity.java
echo 'This is a Test Activity 13 in v3 directory' > Test313Activity.java
echo 'This is a Test Activity 14 in v3 directory' > Test314Activity.java
echo 'This is a Test Activity 15 in v3 directory' > Test315Activity.java
echo 'This is a Test Activity 16 in v3 directory' > Test316Activity.java
echo 'This is a Test Activity 17 in v3 directory' > Test317Activity.java
echo 'This is a Test Activity 18 in v3 directory' > Test318Activity.java
echo 'This is a Test Activity 19 in v3 directory' > Test319Activity.java

cd ~/Desktop/src/com/java/v4/activity
echo 'This is a Test Activity 0 in v4 directory' > Test40Activity.java
echo 'This is a Test Activity 1 in v4 directory' > Test41Activity.java
echo 'This is a Test Activity 2 in v4 directory' > Test42Activity.java
echo 'This is a Test Activity 3 in v4 directory' > Test43Activity.java
echo 'This is a Test Activity 4 in v4 directory' > Test44Activity.java
echo 'This is a Test Activity 5 in v4 directory' > Test45Activity.java
echo 'This is a Test Activity 6 in v4 directory' > Test46Activity.java
echo 'This is a Test Activity 7 in v4 directory' > Test47Activity.java
echo 'This is a Test Activity 8 in v4 directory' > Test48Activity.java
echo 'This is a Test Activity 9 in v4 directory' > Test49Activity.java
echo 'This is a Test Activity 10 in v4 directory' > Test410Activity.java
echo 'This is a Test Activity 11 in v4 directory' > Test411Activity.java
echo 'This is a Test Activity 12 in v4 directory' > Test412Activity.java
echo 'This is a Test Activity 13 in v4 directory' > Test413Activity.java
echo 'This is a Test Activity 14 in v4 directory' > Test414Activity.java
echo 'This is a Test Activity 15 in v4 directory' > Test415Activity.java
echo 'This is a Test Activity 16 in v4 directory' > Test416Activity.java
echo 'This is a Test Activity 17 in v4 directory' > Test417Activity.java
echo 'This is a Test Activity 18 in v4 directory' > Test418Activity.java
echo 'This is a Test Activity 19 in v4 directory' > Test419Activity.java
echo 'This is a Test Activity 20 in v4 directory' > Test420Activity.java
echo 'This is a Test Activity 21 in v4 directory' > Test421Activity.java
echo 'This is a Test Activity 22 in v4 directory' > Test422Activity.java
echo 'This is a Test Activity 23 in v4 directory' > Test423Activity.java
echo 'This is a Test Activity 24 in v4 directory' > Test424Activity.java
echo 'This is a Test Activity 25 in v4 directory' > Test425Activity.java
echo 'This is a Test Activity 26 in v4 directory' > Test426Activity.java
echo 'This is a Test Activity 27 in v4 directory' > Test427Activity.java
echo 'This is a Test Activity 28 in v4 directory' > Test428Activity.java
echo 'This is a Test Activity 29 in v4 directory' > Test429Activity.java
echo 'This is a Test Activity 30 in v4 directory' > Test430Activity.java
echo 'This is a Test Activity 31 in v4 directory' > Test431Activity.java
echo 'This is a Test Activity 32 in v4 directory' > Test432Activity.java
echo 'This is a Test Activity 33 in v4 directory' > Test433Activity.java
echo 'This is a Test Activity 34 in v4 directory' > Test434Activity.java
echo 'This is a Test Activity 35 in v4 directory' > Test435Activity.java
echo 'This is a Test Activity 36 in v4 directory' > Test436Activity.java
echo 'This is a Test Activity 37 in v4 directory' > Test437Activity.java
echo 'This is a Test Activity 38 in v4 directory' > Test438Activity.java
echo 'This is a Test Activity 39 in v4 directory' > Test439Activity.java

cd ~/Desktop/src/com/java/v1/presenter

cd ~/Desktop/src/com/java/v2/presenter
echo 'This is a Test Presenter 0 in v2 directory' > Test20Presenter.java
echo 'This is a Test Presenter 1 in v2 directory' > Test21Presenter.java
echo 'This is a Test Presenter 2 in v2 directory' > Test22Presenter.java
echo 'This is a Test Presenter 3 in v2 directory' > Test23Presenter.java
echo 'This is a Test Presenter 4 in v2 directory' > Test24Presenter.java
echo 'This is a Test Presenter 5 in v2 directory' > Test25Presenter.java
echo 'This is a Test Presenter 6 in v2 directory' > Test26Presenter.java
echo 'This is a Test Presenter 7 in v2 directory' > Test27Presenter.java
echo 'This is a Test Presenter 8 in v2 directory' > Test28Presenter.java
echo 'This is a Test Presenter 9 in v2 directory' > Test29Presenter.java
echo 'This is a Test Presenter 10 in v2 directory' > Test210Presenter.java
echo 'This is a Test Presenter 11 in v2 directory' > Test211Presenter.java
echo 'This is a Test Presenter 12 in v2 directory' > Test212Presenter.java
echo 'This is a Test Presenter 13 in v2 directory' > Test213Presenter.java
echo 'This is a Test Presenter 14 in v2 directory' > Test214Presenter.java
echo 'This is a Test Presenter 15 in v2 directory' > Test215Presenter.java
echo 'This is a Test Presenter 16 in v2 directory' > Test216Presenter.java
echo 'This is a Test Presenter 17 in v2 directory' > Test217Presenter.java
echo 'This is a Test Presenter 18 in v2 directory' > Test218Presenter.java
echo 'This is a Test Presenter 19 in v2 directory' > Test219Presenter.java
echo 'This is a Test Presenter 20 in v2 directory' > Test220Presenter.java
echo 'This is a Test Presenter 21 in v2 directory' > Test221Presenter.java
echo 'This is a Test Presenter 22 in v2 directory' > Test222Presenter.java
echo 'This is a Test Presenter 23 in v2 directory' > Test223Presenter.java
echo 'This is a Test Presenter 24 in v2 directory' > Test224Presenter.java
echo 'This is a Test Presenter 25 in v2 directory' > Test225Presenter.java
echo 'This is a Test Presenter 26 in v2 directory' > Test226Presenter.java
echo 'This is a Test Presenter 27 in v2 directory' > Test227Presenter.java
echo 'This is a Test Presenter 28 in v2 directory' > Test228Presenter.java
echo 'This is a Test Presenter 29 in v2 directory' > Test229Presenter.java
echo 'This is a Test Presenter 30 in v2 directory' > Test230Presenter.java
echo 'This is a Test Presenter 31 in v2 directory' > Test231Presenter.java
echo 'This is a Test Presenter 32 in v2 directory' > Test232Presenter.java
echo 'This is a Test Presenter 33 in v2 directory' > Test233Presenter.java
echo 'This is a Test Presenter 34 in v2 directory' > Test234Presenter.java
echo 'This is a Test Presenter 35 in v2 directory' > Test235Presenter.java
echo 'This is a Test Presenter 36 in v2 directory' > Test236Presenter.java
echo 'This is a Test Presenter 37 in v2 directory' > Test237Presenter.java
echo 'This is a Test Presenter 38 in v2 directory' > Test238Presenter.java
echo 'This is a Test Presenter 39 in v2 directory' > Test239Presenter.java

cd ~/Desktop/src/com/java/v3/presenter
echo 'This is a Test Presenter 20 in v3 directory' > Test320Presenter.java
echo 'This is a Test Presenter 21 in v3 directory' > Test321Presenter.java
echo 'This is a Test Presenter 22 in v3 directory' > Test322Presenter.java
echo 'This is a Test Presenter 23 in v3 directory' > Test323Presenter.java
echo 'This is a Test Presenter 24 in v3 directory' > Test324Presenter.java
echo 'This is a Test Presenter 25 in v3 directory' > Test325Presenter.java
echo 'This is a Test Presenter 26 in v3 directory' > Test326Presenter.java
echo 'This is a Test Presenter 27 in v3 directory' > Test327Presenter.java
echo 'This is a Test Presenter 28 in v3 directory' > Test328Presenter.java
echo 'This is a Test Presenter 29 in v3 directory' > Test329Presenter.java
echo 'This is a Test Presenter 30 in v3 directory' > Test330Presenter.java
echo 'This is a Test Presenter 31 in v3 directory' > Test331Presenter.java
echo 'This is a Test Presenter 32 in v3 directory' > Test332Presenter.java
echo 'This is a Test Presenter 33 in v3 directory' > Test333Presenter.java
echo 'This is a Test Presenter 34 in v3 directory' > Test334Presenter.java
echo 'This is a Test Presenter 35 in v3 directory' > Test335Presenter.java
echo 'This is a Test Presenter 36 in v3 directory' > Test336Presenter.java
echo 'This is a Test Presenter 37 in v3 directory' > Test337Presenter.java
echo 'This is a Test Presenter 38 in v3 directory' > Test338Presenter.java
echo 'This is a Test Presenter 39 in v3 directory' > Test339Presenter.java

cd ~/Desktop/src/com/java/v4/presenter
echo 'This is a Test Presenter 0 in v4 directory' > Test40Presenter.java
echo 'This is a Test Presenter 1 in v4 directory' > Test41Presenter.java
echo 'This is a Test Presenter 2 in v4 directory' > Test42Presenter.java
echo 'This is a Test Presenter 3 in v4 directory' > Test43Presenter.java
echo 'This is a Test Presenter 4 in v4 directory' > Test44Presenter.java
echo 'This is a Test Presenter 5 in v4 directory' > Test45Presenter.java
echo 'This is a Test Presenter 6 in v4 directory' > Test46Presenter.java
echo 'This is a Test Presenter 7 in v4 directory' > Test47Presenter.java
echo 'This is a Test Presenter 8 in v4 directory' > Test48Presenter.java
echo 'This is a Test Presenter 9 in v4 directory' > Test49Presenter.java
echo 'This is a Test Presenter 10 in v4 directory' > Test410Presenter.java
echo 'This is a Test Presenter 11 in v4 directory' > Test411Presenter.java
echo 'This is a Test Presenter 12 in v4 directory' > Test412Presenter.java
echo 'This is a Test Presenter 13 in v4 directory' > Test413Presenter.java
echo 'This is a Test Presenter 14 in v4 directory' > Test414Presenter.java
echo 'This is a Test Presenter 15 in v4 directory' > Test415Presenter.java
echo 'This is a Test Presenter 16 in v4 directory' > Test416Presenter.java
echo 'This is a Test Presenter 17 in v4 directory' > Test417Presenter.java
echo 'This is a Test Presenter 18 in v4 directory' > Test418Presenter.java
echo 'This is a Test Presenter 19 in v4 directory' > Test419Presenter.java
echo 'This is a Test Presenter 20 in v4 directory' > Test420Presenter.java
echo 'This is a Test Presenter 21 in v4 directory' > Test421Presenter.java
echo 'This is a Test Presenter 22 in v4 directory' > Test422Presenter.java
echo 'This is a Test Presenter 23 in v4 directory' > Test423Presenter.java
echo 'This is a Test Presenter 24 in v4 directory' > Test424Presenter.java
echo 'This is a Test Presenter 25 in v4 directory' > Test425Presenter.java
echo 'This is a Test Presenter 26 in v4 directory' > Test426Presenter.java
echo 'This is a Test Presenter 27 in v4 directory' > Test427Presenter.java
echo 'This is a Test Presenter 28 in v4 directory' > Test428Presenter.java
echo 'This is a Test Presenter 29 in v4 directory' > Test429Presenter.java
echo 'This is a Test Presenter 30 in v4 directory' > Test430Presenter.java
echo 'This is a Test Presenter 31 in v4 directory' > Test431Presenter.java
echo 'This is a Test Presenter 32 in v4 directory' > Test432Presenter.java
echo 'This is a Test Presenter 33 in v4 directory' > Test433Presenter.java
echo 'This is a Test Presenter 34 in v4 directory' > Test434Presenter.java
echo 'This is a Test Presenter 35 in v4 directory' > Test435Presenter.java
echo 'This is a Test Presenter 36 in v4 directory' > Test436Presenter.java
echo 'This is a Test Presenter 37 in v4 directory' > Test437Presenter.java
echo 'This is a Test Presenter 38 in v4 directory' > Test438Presenter.java
echo 'This is a Test Presenter 39 in v4 directory' > Test439Presenter.java

